# service for spring boot microservice adverseaction
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  ports:
    - port: 8003
  selector:
    app: portfolio-service
    project: bootcamp99