# service for spring boot microservice adverseaction
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8001
  selector:
    app: user-service
    project: bootcamp99