# service for spring boot microservice adverseaction
apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  ports:
    - port: 8004
  selector:
    app: wallet-service
    project: bootcamp99