# deployment for spring boot microservice api-gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bootcamp99
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: api-gateway
      project: bootcamp99
  template:
    metadata:
      labels:
        app: api-gateway
        project: bootcamp99
    spec:
      containers:
        - name: api-gateway-container
          image: ghcr.io/ishtiaqsamdani007/bc-99-backend-api-gateway:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 4000       
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://bc99be.bootcamp64.tk/eureka/

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://ac4775e3c659f466ab6132a21a6a0aaa-63b7ad61d7cdd357.elb.us-east-1.amazonaws.com:3306/minet?user=root
      
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@99!
      
      imagePullSecrets:
        - name: my-docker-secret