# deployment for spring boot microservice user-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: bootcamp99
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: user-service
      project: bootcamp99
  template:
    metadata:
      labels:
        app: user-service
        project: bootcamp99
    spec:
      containers:
        - name: user-service-container
          image: ghcr.io/ishtiaqsamdani007/bc-99-backend-user-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8001       
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://bc99be.bootcamp64.tk/eureka/

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://ac4775e3c659f466ab6132a21a6a0aaa-63b7ad61d7cdd357.elb.us-east-1.amazonaws.com:3306/minet?user=root
      
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@99!
      
      imagePullSecrets:
        - name: my-docker-secret