server:
  port: 4000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins: "https://bc99fe.bootcamp64.tk/"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: CRYPTOCURRENCY-SERVICE
          uri: lb://CRYPTOCURRENCY-SERVICE
          predicates:
            - Path=/cryptocurrencies/**
          filters:
            - AuthenticationFilter
        - id: PORTFOLIO-SERVICE
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/portfolios/**
          filters:
            - AuthenticationFilter
        - id: WALLET-SERVICE
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/wallets/**
          filters:
            - AuthenticationFilter
        - id: WATCHLIST-SERVICE
          uri: lb://WATCHLIST-SERVICE
          predicates:
            - Path=/watchlist/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost