apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: bootcamp99
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: database
    project: bootcamp99
  